### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by qnikst**

### CODE REVIEW

**Comment by tdietert** [comment]
Ahh, are you getting rid of explicit support for GHC 7.10 and 8.01?

**Comment by qnikst** [comment]
I think ghc-7.10 will gone, and will see how much work do I need to make everything work on 8.0.1, ideally I want to keep 3 latest major release support.

Currently work need to be adopted even for the latest

File: src/Control/Distributed/Process/ManagedProcess/Internal/Types.hs [hunk 1]
```diff
@@ -287,6 +287,11 @@ instance forall s . MonadMask (GenProcess s) where
         (a', _) <- lift $ restoreP $ runProcess ourSTate p2
         return a'
 
+  generalBracket acquire release inner = GenProcess $ 
+    generalBracket (unManaged acquire)
+                   (\a e -> unManaged $ release a e)
+                   (unManaged . inner)
+
```
Comment (tdietert) [inline src/Control/Distributed/Process/ManagedProcess/Internal/Types.hs:294]: All deps of this package (at least `distributed-process-supervisor` and `uplink`) break on lts-11.13 now because of `exceptions-0.10.0`. Why did you roll over to that specific version? This function `generalBracket` is not used anywhere, nor is it exported.

When I try to build my fork of `distributed-process-supervisor` i get:
```
    /tmp/stack2537/distributed-process-client-server-0.2.5/src/Control/Distributed/Process/ManagedProcess/Internal/Types.hs:290:3: error:
        ‘generalBracket’ is not a (visible) method of class ‘MonadMask’
        |
    290 |   generalBracket acquire release inner = GenProcess $ 
        | 
```

Comment (tdietert) [reply src/Control/Distributed/Process/ManagedProcess/Internal/Types.hs:294]: Ahh, well, I'm sure lts-11.14 will have `distributed-process-0.7.4` which is what _needs_ `exceptions-0.10.0`. This is ok :+1:

Comment (qnikst) [reply src/Control/Distributed/Process/ManagedProcess/Internal/Types.hs:294]: Ok, let me add backward compatibility with older exceptions. I've added that because I didn't want to introduce upper bound on the exceptions package. Also generalBracket is used in `bracket` code, and is proper solution for the state monad.

Comment (tdietert) [reply src/Control/Distributed/Process/ManagedProcess/Internal/Types.hs:294]: I think the issue is that `distributed-process-0.7.4` demands `exceptions >= 0.10.0`. Since this is the case, I _think_ that means you'd have to remove `distributed-process-0.7.4` from the extra-deps, because otherwise it will compain that `exceptions >= 0.10.0` dep constraint is not met.

Comment (tdietert) [reply src/Control/Distributed/Process/ManagedProcess/Internal/Types.hs:294]: If you remove both, the stack resolver `lts-11.13` will default to `distributed-process-0.7.3` and `exceptions-0.8.3`, hopefully.
